# Generated by Django 4.2.29 on 2026-03-23 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('stream_created', 'Stream Created'), ('stream_started', 'Stream Started'), ('stream_paused', 'Stream Paused'), ('stream_cancelled', 'Stream Cancelled'), ('withdrawal', 'Withdrawal'), ('milestone_approved', 'Milestone Approved'), ('milestone_paid', 'Milestone Paid'), ('wallet_created', 'Wallet Created'), ('asset_created', 'Asset Created'), ('investment_created', 'Investment Created'), ('credit_borrowed', 'Credit Borrowed'), ('credit_repaid', 'Credit Repaid'), ('goal_created', 'Goal Created'), ('goal_funded', 'Goal Funded'), ('split_updated', 'Split Updated')], max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('withdrawal', 'Withdrawal'), ('milestone', 'Milestone Payment'), ('deposit', 'Deposit'), ('investment', 'Investment'), ('credit_borrow', 'Credit Borrow'), ('credit_repay', 'Credit Repay'), ('goal_allocation', 'Goal Allocation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payroll.payrollstream'),
        ),
        migrations.CreateModel(
            name='SalaryWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('locked_balance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('invested_balance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_earned', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('total_withdrawn', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'salary_wallets',
            },
        ),
        migrations.CreateModel(
            name='MicroInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('current_value', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('roi_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('auto_invest_percentage', models.DecimalField(decimal_places=2, default=0, help_text='% of salary to auto-invest', max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('withdrawn', 'Withdrawn')], default='active', max_length=10)),
                ('tx_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'micro_investments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('travel', 'Travel'), ('emergency', 'Emergency'), ('education', 'Education'), ('gadget', 'Gadget'), ('custom', 'Custom')], default='custom', max_length=15)),
                ('target_amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('current_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('auto_allocate_percentage', models.DecimalField(decimal_places=2, default=0, help_text='% of salary to auto-allocate', max_digits=5)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('borrowed_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('repaid_amount', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Annual %', max_digits=5)),
                ('auto_repay_percentage', models.DecimalField(decimal_places=2, default=10, help_text='% of salary for auto-repayment', max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('repaid', 'Fully Repaid'), ('defaulted', 'Defaulted')], default='active', max_length=10)),
                ('tx_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_lines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_lines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoSplitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('savings', 'Savings'), ('rent', 'Rent / Housing'), ('investment', 'Investment'), ('emergency', 'Emergency Fund'), ('spending', 'Spending'), ('custom', 'Custom')], default='custom', max_length=15)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of salary', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auto_split_rules',
                'ordering': ['-percentage'],
            },
        ),
    ]
